import { useEffect, useState } from 'react';
import type { FormEvent } from 'react';
import { Send, BrainCircuit } from 'lucide-react';
import { api } from '../../services/api';
import { Card, CardContent, CardHeader, CardTitle } from '../../components/ui/Card';

export function CopilotPage() {
  const [conversations, setConversations] = useState<any[]>([]); const [active, setActive] = useState<any>(null); const [text, setText] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { api.copilot.conversations().then(setConversations).catch(e => setError(e.message)); }, []);
  async function start() { try { const c=await api.copilot.create(); setConversations(x=>[c,...x]); setActive({...c,messages:[]}); } catch(e:any){setError(e.message);} }
  async function submit(e:FormEvent) { e.preventDefault(); if(!text.trim()||!active)return; setBusy(true);setError('');try { const result=await api.copilot.send(active.id,text); setActive((c:any)=>({...c,messages:[...c.messages,{sender:'user',content:text},{sender:'copilot',content:result.content,provider_used:result.provider_used}]}));setText(''); } catch(e:any){setError(e.message);}finally{setBusy(false);} }
  return <div className="flex flex-col gap-6 h-[calc(100vh-8rem)]"><div><h1 className="text-2xl font-bold text-primary flex items-center gap-2"><BrainCircuit className="text-accent"/>Engineering Copilot</h1><p className="text-sm text-slate-400 mt-1">Grounded maintenance analysis from your telemetry, ML findings, and documents.</p></div><div className="grid grid-cols-1 md:grid-cols-4 gap-4 flex-1 min-h-0"><Card className="md:col-span-1"><CardHeader><CardTitle>Conversations</CardTitle></CardHeader><CardContent className="space-y-2"><button onClick={start} className="w-full rounded bg-accent px-3 py-2 text-sm font-medium text-slate-950">New conversation</button>{conversations.length===0&&<p className="text-sm text-slate-500 py-3">No conversations yet.</p>}{conversations.map(c=><button key={c.id} onClick={()=>api.copilot.get(c.id).then(setActive).catch(e=>setError(e.message))} className="w-full text-left p-2 rounded hover:bg-slate-800 text-sm text-slate-300">{c.title}</button>)}</CardContent></Card><Card className="md:col-span-3 flex flex-col min-h-0"><CardContent className="flex-1 overflow-auto space-y-4 pt-5">{!active?<p className="text-slate-500 text-sm">Start a conversation to ask a machine-aware engineering question.</p>:active.messages?.map((m:any,i:number)=><div key={i} className={m.sender==='user'?"ml-10 p-3 bg-slate-800 rounded":"mr-10 p-3 bg-slate-950 border border-slate-800 rounded"}><div className="text-xs uppercase text-slate-500 mb-1">{m.sender}{m.provider_used?` · ${m.provider_used}`:''}</div><p className="text-sm text-slate-200 whitespace-pre-wrap">{m.content}</p></div>)}</CardContent><form onSubmit={submit} className="p-4 border-t border-slate-800 flex gap-2"><input value={text} onChange={e=>setText(e.target.value)} disabled={!active||busy} placeholder={active?'Ask about the supplied engineering context…':'Create a conversation first'} className="flex-1 bg-slate-950 border border-slate-700 rounded px-3 py-2 text-sm"/><button disabled={!active||busy} className="p-2 bg-accent text-slate-950 rounded"><Send className="w-4 h-4"/></button></form>{error&&<p className="px-4 pb-3 text-xs text-red-400">{error}</p>}</Card></div></div>;
}
